In [3]:
import numpy as a
# Python program to demonstrate
# basic array characteristics
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [ ]:
# numpy is terms as the numerical python,numerical means numbers numby  is libraryes it cointains many built in function ,mainly funcion is used  many times as the librabries book 

# it is the open sources 

# multidimesion arrays
# homogenus---all data is in same form...
# hetro genus---all data type is not in same form
# in case of numpy we can handel string#

# in the list we can put the hetro 
# numpy dimesion called axis 
# mainly axis is same as the matrix  row or colum ko bolte h
# array is the collection of same data type


In [ ]:
# reason for using numpy

# numpy handel array 
# it provide a good storage 

In [ ]:
Array
contigous memory
numpy array class is called ndarray
for numpy you must create array  first


In [6]:
import numpy as np
import sys
arr1=np.array([1,2,3,4,56,7,89,8])
print(arr1)
print(type(arr1))
print(sys.getsizeof(arr1))
lst1=[4,5,7,8,9,55,]


[ 1  2  3  4 56  7 89  8]
<class 'numpy.ndarray'>
136


In [ ]:
exam ka ka liye imp haa

diffrent attribuutes of numpy

In [8]:
#1d array----list should be 1d ex  lst=[1,3,4,5,6]
import numpy as np
lst=[1,3,4,5,6]
arr1=np.array(lst)
print(arr1)
print(arr1.dtype) #data  type
print(arr1.ndim) #no of dimesion 
print(arr1.itemsize) # size in bytes of each element

print(arr1.nbytes) #size of whole array
print(arr1.size) # numbers of elements in array 

print(arr1.shape) # oder of the arrays ,means it gives the rows  and coloms ##if colom is 1 it used as deafult it return as  (6,) it means  6 row and 1 colom
print(type(arr1)) 
print(sys.getsizeof(arr1))

[1 3 4 5 6]
int32
1
4
20
5
(5,)
<class 'numpy.ndarray'>
124


In [10]:
import numpy as np
lst=[[1,3,4,5,6],[5,6,4,7,8]]
arr2=np.array(lst)
print(arr2)
print(arr2.dtype) #data  type
print(arr2.ndim) #no of dimesion 
print(arr2.itemsize) # size in bytes of each element

print(arr2.nbytes) #size of whole array
print(arr2.size) # numbers of elements in array 

print(arr2.shape) # oder of the arrays ,means it gives the rows  and coloms ##if colom is 1 it used as deafult it return as  (6,) it means  6 row and 1 colom
print(type(arr2)) 

[[1 3 4 5 6]
 [5 6 4 7 8]]
int32
2
4
40
10
(2, 5)
<class 'numpy.ndarray'>


In [15]:
import numpy as np
lst=[[[1,3,4,5,6],[5,6,4,7,8]],[[12,56,78,89,77],[55,44,56,57,88]]]
arr3=np.array(lst)
print(arr3)
print(arr3.dtype) #data  type
print(arr3.ndim) #no of dimesion 
print(arr3.itemsize) # size in bytes of each element

print(arr3.nbytes) #size of whole array
print(arr3.size) # numbers of elements in array 

print(arr3.shape) # oder of the arrays ,means it gives the rows  and coloms ##if colom is 1 it used as deafult it return as  (6,) it means  6 row and 1 colom
print(type(arr3))

[[[ 1  3  4  5  6]
  [ 5  6  4  7  8]]

 [[12 56 78 89 77]
  [55 44 56 57 88]]]
int32
3
4
80
20
(2, 2, 5)
<class 'numpy.ndarray'>


In [25]:
import numpy as np

arr1=np.array(range(10,21),"int8") #int8 is the 8 bites ==1bytes 
print(arr1)
print(arr1.dtype) #data  type
print(arr1.ndim) #no of dimesion 
print("size type",arr1.itemsize) # size in bytes of each element

print(arr1.nbytes) #size of whole array
print("size",arr1.size) # numbers of elements in array 

print(arr1.shape) # oder of the arrays ,means it gives the rows  and coloms ##if colom is 1 it used as deafult it return as  (6,) it means  6 row and 1 colom
print(type(arr1))



print(arr1[1])
print(arr1[2])
print(arr1[3])
print(arr1[4])
print(arr1[5])
print(arr1[6])

for i in arr1:
    print(i,end="  ")
print()#it is for the change of the lib=ne 

[10 11 12 13 14 15 16 17 18 19 20]
int8
1
size type 1
11
size 11
(11,)
<class 'numpy.ndarray'>
11
12
13
14
15
16
10  11  12  13  14  15  16  17  18  19  20  


In [ ]:
Array ma silicing 1d

In [26]:
import numpy as np
arr1=np.array([12,34,56,45,47,48,59,59,63,47,25])
print(arr1[5:6:2])#[start]
print(arr1[::-1])#reverse the array 
print(arr1[5:6:2])
print(arr1[5:6:2])

[48]
[48]
[48]
[48]


In [40]:
import numpy as np
arr1=np.array([[12,1,3,5],[12,45,65,85],[5,6,6,4],[5,78,98,74]])
print(arr1[1:5,1:4])

[[45 65 85]
 [ 6  6  4]
 [78 98 74]]


In [44]:
#slice create view of the original array
arr1=np.array([12,25,26,24,58,985,7421,21,23,54,65])
print("original without change",arr1)
b=arr1[4:8]
print("sub without change",b)
b[2]=2000
print("sub with change",b)
print("original with change",arr1)

original without change [  12   25   26   24   58  985 7421   21   23   54   65]
sub without change [  58  985 7421   21]
sub with change [  58  985 2000   21]
original with change [  12   25   26   24   58  985 2000   21   23   54   65]


In [ ]:
1d and 2d creation by using function

In [2]:
import  numpy as np
arr1=np.arange(15)
print("1d by using arange",arr1)
arr2=arr1.reshape(3,5)
print("1d to 2d by using reshape  ",arr2)

1d by using arange [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [ ]:
1d to 3d by using reshape

In [49]:
arr1=np.arange(48).reshape(4,12)
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]]


In [ ]:
zero func is used to create null matrix
#null matrix is used to insilization


In [ ]:
#empy matrix cointains raindom vzlue hota h it may or may not be zero it not granted that elements are zero

In [32]:
a=np.zeros((55,12))
print(a)
a=np.ones((55,12))
print(a)
a=np.empty((55,12))
print(a)
arr1 = np.eye(4,7)
print(arr1)
arr3 = np.identity(4)
print(arr3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [37]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
arr2=np.array([[[1,2,3],[4,5,6],[6,7,8]],[[1,0,1],[0,0,1],[1,1,0]]])
print(arr1)
print(arr1.dtype) #data  type
print(arr1.ndim) #no of dimesion 
print(arr1.itemsize) # size in bytes of each element

print(arr1.nbytes) #size of whole array
print(arr1.size) # numbers of elements in array 

print(arr1.shape) # oder of the arrays ,means it gives the rows  and coloms ##if colom is 1 it used as deafult it return as  (6,) it means  6 row and 1 colom
print(type(arr1)) 



[1 2 3 4 5]
[1 2 3 4 5]
int32
1
4
20
5
(5,)
<class 'numpy.ndarray'>


In [38]:
ac=np.arange(10)
print(ac)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
ac=np.array(range(10))
print(ac)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
ac=np.arange(10)
at=ac.reshape(2,5)
print(at)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
ac=np.arange(40)
at=ac.reshape(4,2,5)
print(at)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]


In [59]:
ac=np.arange(40)
a_1=np.resize(ac, (3,2))
print("2d  ",a_1)
a_1=np.resize(ac, (2,3,2))
# a_1=ac.resize(2,5,10)
print("3d  ",a_1)

2d   [[0 1]
 [2 3]
 [4 5]]
3d   [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [65]:
arr2=np.array([[1,2,3],[4,5,6]])
a_1=arr2[0][1]
print(a_1)
a_1=arr2[0,1]
print(a_1)

2
2


In [67]:
arr3=np.array([[[1,2,3],[4,5,6],[6,7,8]],[[1,0,1],[0,0,1],[1,1,0]]])
arr2=arr3[0,2,1]
print(arr2)

7


In [75]:
arr1=np.array([12,34,56,78,3,5,2,7,8,9,11,10,15])
print(arr1[3:10:1])
print(arr1[3::])
print(arr1[::-1])
print(arr1[1:3:])
print("DEKO",arr1[-10:-3:])
print(arr1[10:3:-1])
print(arr1[::])
print(arr1[3::5])
# print(arr1[3:10:0])

[78  3  5  2  7  8  9]
[78  3  5  2  7  8  9 11 10 15]
[15 10 11  9  8  7  2  5  3 78 56 34 12]
[34 56]
DEKO [78  3  5  2  7  8  9]
[11  9  8  7  2  5  3]
[12 34 56 78  3  5  2  7  8  9 11 10 15]
[78  8]


In [76]:
row1 = "34 53  3" 
row2 = "  4 546 "
row3 = ""
row4 = " "
row5 = "5"
row6 = "      "
row7 = "123456789"
row8 = "000000000"
row9 = " 34 76657"

row_list = [list(row1), list(row2), list(row3), list(row4), list(row5), 
list(row6), list(row7), list(row8), list(row9)]

print(np.matrix(row_list))


[[list(['3', '4', ' ', '5', '3', ' ', ' ', '3'])
  list([' ', ' ', '4', ' ', '5', '4', '6', ' ']) list([]) list([' '])
  list(['5']) list([' ', ' ', ' ', ' ', ' ', ' '])
  list(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
  list(['0', '0', '0', '0', '0', '0', '0', '0', '0'])
  list([' ', '3', '4', ' ', '7', '6', '6', '5', '7'])]]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [78]:
a=np.array(range(20,34))
b=np.array(range(20,34))
print(a+b)

[40 42 44 46 48 50 52 54 56 58 60 62 64 66]


In [81]:
ar1=np.arange(18)
print(ar1)
ar2=np.resize(ar1,(6,3))
print(ar2)
ar2=np.resize(ar1,(6,3,2))
print(ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [ ]:
ravel,flater,copy,view,linespace

In [ ]:
#using of random function we create 

In [84]:
import random
import numpy as np
rg=np.random.default_rng()
a1=rg.random((3,4))
print(a1)
a2=a1*10
print(a2)

[[0.31667059 0.15208723 0.81559681 0.57002553]
 [0.46889644 0.00291753 0.06070558 0.11003276]
 [0.79302737 0.09569594 0.27877077 0.18196819]]
[[3.16670587 1.52087228 8.15596813 5.70025527]
 [4.68896441 0.0291753  0.60705584 1.10032763]
 [7.93027368 0.95695941 2.78770766 1.81968186]]


In [88]:
import numpy as np
a=np.identity(2)
b=np.zeros(2)
c=np.diag([7,8])
d=np.eye(2,2)
e=np.block([[a,b],[c,d]])
print(a)
print(a)
print(a)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1